// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 299.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'dor_companion';

  static const String assets_icons_play_icon_2_svg =
      'assets/icons/Play_icon_2.svg';

  static const String assets_icons_ticket_svg = 'assets/icons/Ticket.svg';

  static const String assets_icons_activate_tv_svg =
      'assets/icons/activate_tv.svg';

  static const String assets_icons_add_circle_png =
      'assets/icons/add_circle.png';

  static const String assets_icons_arrow_back_svg =
      'assets/icons/arrow_back.svg';

  static const String assets_icons_arrow_right_alt_svg =
      'assets/icons/arrow_right_alt.svg';

  static const String assets_icons_bookmark_svg = 'assets/icons/bookmark.svg';

  static const String assets_icons_bookmarked_svg =
      'assets/icons/bookmarked.svg';

  static const String assets_icons_brush_svg = 'assets/icons/brush.svg';

  static const String assets_icons_calendar_month_png =
      'assets/icons/calendar_month.png';

  static const String assets_icons_call_svg = 'assets/icons/call.svg';

  static const String assets_icons_cancel_svg = 'assets/icons/cancel.svg';

  static const String assets_icons_chat_svg = 'assets/icons/chat.svg';

  static const String assets_icons_check_circle_svg =
      'assets/icons/check_circle.svg';

  static const String assets_icons_checklist_rtl_svg =
      'assets/icons/checklist_rtl.svg';

  static const String assets_icons_child_care_svg =
      'assets/icons/child_care.svg';

  static const String assets_icons_custom_cursor_svg =
      'assets/icons/custom_cursor.svg';

  static const String assets_icons_delete_svg = 'assets/icons/delete.svg';

  static const String assets_icons_down_arrow_svg =
      'assets/icons/down_arrow.svg';

  static const String assets_icons_email_svg = 'assets/icons/email.svg';

  static const String assets_icons_error_icon_svg =
      'assets/icons/error_icon.svg';

  static const String assets_icons_explorer_membership_icon_svg =
      'assets/icons/explorer_membership_icon.svg';

  static const String assets_icons_icon_about_3sixty_svg =
      'assets/icons/icon_about_3sixty.svg';

  static const String assets_icons_icon_bookmark_svg =
      'assets/icons/icon_bookmark.svg';

  static const String assets_icons_icon_bookmarked_svg =
      'assets/icons/icon_bookmarked.svg';

  static const String assets_icons_icon_devices_svg =
      'assets/icons/icon_devices.svg';

  static const String assets_icons_icon_dislike_svg =
      'assets/icons/icon_dislike.svg';

  static const String assets_icons_icon_disliked_svg =
      'assets/icons/icon_disliked.svg';

  static const String assets_icons_icon_dor_svg = 'assets/icons/icon_dor.svg';

  static const String assets_icons_icon_dor_play_svg =
      'assets/icons/icon_dor_play.svg';

  static const String assets_icons_icon_dorplay_png =
      'assets/icons/icon_dorplay.png';

  static const String assets_icons_icon_edit_pensicle_svg =
      'assets/icons/icon_edit_pensicle.svg';

  static const String assets_icons_icon_favorite_svg =
      'assets/icons/icon_favorite.svg';

  static const String assets_icons_icon_find_svg = 'assets/icons/icon_find.svg';

  static const String assets_icons_icon_home_svg = 'assets/icons/icon_home.svg';

  static const String assets_icons_icon_library_svg =
      'assets/icons/icon_library.svg';

  static const String assets_icons_icon_live_svg = 'assets/icons/icon_live.svg';

  static const String assets_icons_icon_news_svg = 'assets/icons/icon_news.svg';

  static const String assets_icons_icon_not_favorite_svg =
      'assets/icons/icon_not_favorite.svg';

  static const String assets_icons_icon_not_seen_svg =
      'assets/icons/icon_not_seen.svg';

  static const String assets_icons_icon_privacy_policy_svg =
      'assets/icons/icon_privacy_policy.svg';

  static const String assets_icons_icon_remote_svg =
      'assets/icons/icon_remote.svg';

  static const String assets_icons_icon_report_svg =
      'assets/icons/icon_report.svg';

  static const String assets_icons_icon_seen_svg = 'assets/icons/icon_seen.svg';

  static const String assets_icons_icon_spoke_svg =
      'assets/icons/icon_spoke.svg';

  static const String assets_icons_icon_sports_svg =
      'assets/icons/icon_sports.svg';

  static const String assets_icons_icon_sports_esports_svg =
      'assets/icons/icon_sports_esports.svg';

  static const String assets_icons_icon_terms_of_use_svg =
      'assets/icons/icon_terms_of_use.svg';

  static const String assets_icons_icon_wellness_svg =
      'assets/icons/icon_wellness.svg';

  static const String assets_icons_info_svg = 'assets/icons/info.svg';

  static const String assets_icons_left_arrow_svg =
      'assets/icons/left_arrow.svg';

  static const String assets_icons_manage_device_svg =
      'assets/icons/manage_device.svg';

  static const String assets_icons_mic_svg = 'assets/icons/mic.svg';

  static const String assets_icons_notification_svg =
      'assets/icons/notification.svg';

  static const String assets_icons_play_icon_png = 'assets/icons/play_icon.png';

  static const String assets_icons_privacy_svg = 'assets/icons/privacy.svg';

  static const String assets_icons_profile_edit_svg =
      'assets/icons/profile_edit.svg';

  static const String assets_icons_rocket_launch_png =
      'assets/icons/rocket_launch.png';

  static const String assets_icons_search_svg = 'assets/icons/search.svg';

  static const String assets_icons_select_catagory_svg =
      'assets/icons/select_catagory.svg';

  static const String assets_icons_selected_svg = 'assets/icons/selected.svg';

  static const String assets_icons_share_png = 'assets/icons/share.png';

  static const String assets_icons_solar_reel_broken_svg =
      'assets/icons/solar_reel-broken.svg';

  static const String assets_icons_splash_png = 'assets/icons/splash.png';

  static const String assets_icons_subscriber_agreement_svg =
      'assets/icons/subscriber_agreement.svg';

  static const String assets_icons_supervisor_account_png =
      'assets/icons/supervisor_account.png';

  static const String assets_icons_tick_arrow_svg =
      'assets/icons/tick_arrow.svg';

  static const String assets_icons_timer_png = 'assets/icons/timer.png';

  static const String assets_icons_translate_svg = 'assets/icons/translate.svg';

  static const String assets_icons_tv_issue_svg = 'assets/icons/tv_issue.svg';

  static const String assets_icons_unselected_svg =
      'assets/icons/unselected.svg';

  static const String assets_icons_whatsapp_svg = 'assets/icons/whatsapp.svg';

  static const String assets_images_add_to_watchlist_svg =
      'assets/images/add_to_watchlist.svg';

  static const String assets_images_amazon_prime_amazon_prime_svg =
      'assets/images/amazon_prime/Amazon prime.svg';

  static const String assets_images_amazon_prime_prime_video_svg =
      'assets/images/amazon_prime/Prime_video.svg';

  static const String assets_images_amazon_prime_amazon_prime_background_png =
      'assets/images/amazon_prime/amazon_prime_background.png';

  static const String assets_images_amazon_prime_delivery_prime_png =
      'assets/images/amazon_prime/delivery_prime.png';

  static const String assets_images_amazon_prime_popcorn_new_png =
      'assets/images/amazon_prime/popcorn_new.png';

  static const String assets_images_app_logos_aha_jpg =
      'assets/images/app_logos/aha.jpg';

  static const String assets_images_app_logos_altbalaji_jpg =
      'assets/images/app_logos/altbalaji.jpg';

  static const String assets_images_app_logos_dorplay_png =
      'assets/images/app_logos/dorplay.png';

  static const String assets_images_app_logos_epicon_png =
      'assets/images/app_logos/epicon.png';

  static const String assets_images_app_logos_erosnow_png =
      'assets/images/app_logos/erosnow.png';

  static const String assets_images_app_logos_hoichoi_png =
      'assets/images/app_logos/hoichoi.png';

  static const String assets_images_app_logos_hotstar_jpg =
      'assets/images/app_logos/hotstar.jpg';

  static const String assets_images_app_logos_hungama_png =
      'assets/images/app_logos/hungama.png';

  static const String assets_images_app_logos_icon_edit_png =
      'assets/images/app_logos/icon_edit.png';

  static const String assets_images_app_logos_jiocinema_png =
      'assets/images/app_logos/jiocinema.png';

  static const String assets_images_app_logos_lionsgate_png =
      'assets/images/app_logos/lionsgate.png';

  static const String assets_images_app_logos_mxplayer_png =
      'assets/images/app_logos/mxplayer.png';

  static const String assets_images_app_logos_netflix_png =
      'assets/images/app_logos/netflix.png';

  static const String assets_images_app_logos_prime_jpg =
      'assets/images/app_logos/prime.jpg';

  static const String assets_images_app_logos_sonyliv_webp =
      'assets/images/app_logos/sonyliv.webp';

  static const String assets_images_app_logos_sunnxt_png =
      'assets/images/app_logos/sunnxt.png';

  static const String assets_images_app_logos_voot_png =
      'assets/images/app_logos/voot.png';

  static const String assets_images_app_logos_youtube_jpg =
      'assets/images/app_logos/youtube.jpg';

  static const String assets_images_app_logos_yupptv_jpg =
      'assets/images/app_logos/yupptv.jpg';

  static const String assets_images_app_logos_zee5_jpg =
      'assets/images/app_logos/zee5.jpg';

  static const String assets_images_appbar_images_appbar_bell_svg =
      'assets/images/appbar_images/appbar_bell.svg';

  static const String assets_images_appbar_images_avatar_top_png =
      'assets/images/appbar_images/avatar_top.png';

  static const String assets_images_appbar_images_go_premium_png =
      'assets/images/appbar_images/go_premium.png';

  static const String assets_images_appbar_images_go_premium_svg =
      'assets/images/appbar_images/go_premium.svg';

  static const String assets_images_appbar_images_icon_dor_play_svg =
      'assets/images/appbar_images/icon_dor_play.svg';

  static const String assets_images_appbar_images_search_svg =
      'assets/images/appbar_images/search.svg';

  static const String assets_images_appbar_images_subscribe_svg =
      'assets/images/appbar_images/subscribe.svg';

  static const String assets_images_appbar_images_topnav_avatar_svg =
      'assets/images/appbar_images/topnav_avatar.svg';

  static const String assets_images_appbar_images_upgrade_svg =
      'assets/images/appbar_images/upgrade.svg';

  static const String assets_images_genre_card_and_mood_card_images_action_png =
      'assets/images/genre_card_and_mood_card_images/Action.png';

  static const String
      assets_images_genre_card_and_mood_card_images_adventure_png =
      'assets/images/genre_card_and_mood_card_images/Adventure.png';

  static const String
      assets_images_genre_card_and_mood_card_images_annoyed_svg =
      'assets/images/genre_card_and_mood_card_images/Annoyed.svg';

  static const String assets_images_genre_card_and_mood_card_images_bored_svg =
      'assets/images/genre_card_and_mood_card_images/Bored.svg';

  static const String assets_images_genre_card_and_mood_card_images_comedy_png =
      'assets/images/genre_card_and_mood_card_images/Comedy.png';

  static const String assets_images_genre_card_and_mood_card_images_crime_png =
      'assets/images/genre_card_and_mood_card_images/Crime.png';

  static const String
      assets_images_genre_card_and_mood_card_images_curious_svg =
      'assets/images/genre_card_and_mood_card_images/Curious.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_documentary_png =
      'assets/images/genre_card_and_mood_card_images/Documentary.png';

  static const String assets_images_genre_card_and_mood_card_images_drama_png =
      'assets/images/genre_card_and_mood_card_images/Drama.png';

  static const String
      assets_images_genre_card_and_mood_card_images_energetic_svg =
      'assets/images/genre_card_and_mood_card_images/Energetic.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_excited_svg =
      'assets/images/genre_card_and_mood_card_images/Excited.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_fantasy_png =
      'assets/images/genre_card_and_mood_card_images/Fantasy.png';

  static const String
      assets_images_genre_card_and_mood_card_images_frame_2147224692_png =
      'assets/images/genre_card_and_mood_card_images/Frame 2147224692.png';

  static const String assets_images_genre_card_and_mood_card_images_happy_svg =
      'assets/images/genre_card_and_mood_card_images/Happy.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_historical_png =
      'assets/images/genre_card_and_mood_card_images/Historical.png';

  static const String assets_images_genre_card_and_mood_card_images_horror_png =
      'assets/images/genre_card_and_mood_card_images/Horror.png';

  static const String
      assets_images_genre_card_and_mood_card_images_inspired_svg =
      'assets/images/genre_card_and_mood_card_images/Inspired.svg';

  static const String assets_images_genre_card_and_mood_card_images_kids_png =
      'assets/images/genre_card_and_mood_card_images/Kids.png';

  static const String
      assets_images_genre_card_and_mood_card_images_musical_png =
      'assets/images/genre_card_and_mood_card_images/Musical.png';

  static const String
      assets_images_genre_card_and_mood_card_images_mystery_png =
      'assets/images/genre_card_and_mood_card_images/Mystery.png';

  static const String
      assets_images_genre_card_and_mood_card_images_nostalgia_svg =
      'assets/images/genre_card_and_mood_card_images/Nostalgia.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_philosophical_svg =
      'assets/images/genre_card_and_mood_card_images/Philosophical.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_relaxed_svg =
      'assets/images/genre_card_and_mood_card_images/Relaxed.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_romance_png =
      'assets/images/genre_card_and_mood_card_images/Romance.png';

  static const String
      assets_images_genre_card_and_mood_card_images_romantic_svg =
      'assets/images/genre_card_and_mood_card_images/Romantic.svg';

  static const String assets_images_genre_card_and_mood_card_images_sci_fi_png =
      'assets/images/genre_card_and_mood_card_images/Sci-fi.png';

  static const String
      assets_images_genre_card_and_mood_card_images_science_png =
      'assets/images/genre_card_and_mood_card_images/Science.png';

  static const String
      assets_images_genre_card_and_mood_card_images_stressed_svg =
      'assets/images/genre_card_and_mood_card_images/Stressed.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_thriller_png =
      'assets/images/genre_card_and_mood_card_images/Thriller.png';

  static const String assets_images_genre_card_and_mood_card_images_war_png =
      'assets/images/genre_card_and_mood_card_images/War.png';

  static const String assets_images_genre_card_and_mood_card_images_scared_svg =
      'assets/images/genre_card_and_mood_card_images/scared.svg';

  static const String
      assets_images_genre_card_and_mood_card_images_serious_svg =
      'assets/images/genre_card_and_mood_card_images/serious.svg';

  static const String assets_images_home_images_card_png =
      'assets/images/home_images/Card.png';

  static const String assets_images_home_images_arrow_right_alt_svg =
      'assets/images/home_images/arrow_right_alt.svg';

  static const String assets_images_home_images_blue_play_button_svg =
      'assets/images/home_images/blue_play_button.svg';

  static const String assets_images_home_images_dtv_icon_svg =
      'assets/images/home_images/dtv_icon.svg';

  static const String assets_images_home_images_dtv_icon_unselected_svg =
      'assets/images/home_images/dtv_icon_unselected.svg';

  static const String assets_images_home_images_filter_icon_live_tv_svg =
      'assets/images/home_images/filter_icon_live_tv.svg';

  static const String assets_images_home_images_game_png =
      'assets/images/home_images/game.png';

  static const String assets_images_home_images_kids_png =
      'assets/images/home_images/kids.png';

  static const String assets_images_home_images_live_news_tab_png =
      'assets/images/home_images/live_news_tab.png';

  static const String assets_images_home_images_live_news_tab_icon_svg =
      'assets/images/home_images/live_news_tab_icon.svg';

  static const String assets_images_home_images_movie_png =
      'assets/images/home_images/movie.png';

  static const String assets_images_home_images_news_png =
      'assets/images/home_images/news.png';

  static const String assets_images_home_images_newspaper_png =
      'assets/images/home_images/newspaper.png';

  static const String assets_images_home_images_popcorn_png =
      'assets/images/home_images/popcorn.png';

  static const String assets_images_home_images_select_profile_png =
      'assets/images/home_images/select_profile.png';

  static const String assets_images_home_images_selected_game_svg =
      'assets/images/home_images/selected_game.svg';

  static const String assets_images_home_images_selected_highlight_svg =
      'assets/images/home_images/selected_highlight.svg';

  static const String assets_images_home_images_selected_home_svg =
      'assets/images/home_images/selected_home.svg';

  static const String assets_images_home_images_selected_live_svg =
      'assets/images/home_images/selected_live.svg';

  static const String assets_images_home_images_selected_news_svg =
      'assets/images/home_images/selected_news.svg';

  static const String assets_images_home_images_selected_profile_svg =
      'assets/images/home_images/selected_profile.svg';

  static const String assets_images_home_images_selected_sport_svg =
      'assets/images/home_images/selected_sport.svg';

  static const String assets_images_home_images_sport_png =
      'assets/images/home_images/sport.png';

  static const String assets_images_home_images_sport_svg =
      'assets/images/home_images/sport.svg';

  static const String assets_images_home_images_sports_png =
      'assets/images/home_images/sports.png';

  static const String assets_images_home_images_television_png =
      'assets/images/home_images/television.png';

  static const String assets_images_home_images_tv_guide_icon_svg =
      'assets/images/home_images/tv_guide_icon.svg';

  static const String assets_images_home_images_tv_guide_tab_png =
      'assets/images/home_images/tv_guide_tab.png';

  static const String assets_images_home_images_unselect_profile_png =
      'assets/images/home_images/unselect_profile.png';

  static const String assets_images_home_images_unselected_game_svg =
      'assets/images/home_images/unselected_game.svg';

  static const String assets_images_home_images_unselected_home_svg =
      'assets/images/home_images/unselected_home.svg';

  static const String assets_images_home_images_unselected_live_svg =
      'assets/images/home_images/unselected_live.svg';

  static const String assets_images_home_images_unselected_news_svg =
      'assets/images/home_images/unselected_news.svg';

  static const String assets_images_home_images_unselected_profile_svg =
      'assets/images/home_images/unselected_profile.svg';

  static const String assets_images_home_images_unselected_sport_svg =
      'assets/images/home_images/unselected_sport.svg';

  static const String assets_images_live_tv_business_news_image_png =
      'assets/images/live_tv/business_news_image.png';

  static const String assets_images_live_tv_comedy_image_png =
      'assets/images/live_tv/comedy_image.png';

  static const String assets_images_live_tv_devotional_image_png =
      'assets/images/live_tv/devotional_image.png';

  static const String assets_images_live_tv_entertainment_image_png =
      'assets/images/live_tv/entertainment_image.png';

  static const String assets_images_live_tv_finance_image_png =
      'assets/images/live_tv/finance_image.png';

  static const String assets_images_live_tv_food_lifestyle_image_png =
      'assets/images/live_tv/food_lifestyle_image.png';

  static const String assets_images_live_tv_fun_games_image_png =
      'assets/images/live_tv/fun_games_image.png';

  static const String assets_images_live_tv_infotainment_image_png =
      'assets/images/live_tv/infotainment_image.png';

  static const String assets_images_live_tv_kids_image_png =
      'assets/images/live_tv/kids_image.png';

  static const String assets_images_live_tv_live_icon_svg =
      'assets/images/live_tv/live_icon.svg';

  static const String assets_images_live_tv_movies_image_png =
      'assets/images/live_tv/movies_image.png';

  static const String assets_images_live_tv_music_image_png =
      'assets/images/live_tv/music_image.png';

  static const String assets_images_live_tv_news_image_png =
      'assets/images/live_tv/news_image.png';

  static const String assets_images_live_tv_no_channel_found_image_png =
      'assets/images/live_tv/no_channel_found_image.png';

  static const String assets_images_live_tv_no_internet_image_png =
      'assets/images/live_tv/no_internet_image.png';

  static const String assets_images_live_tv_play_icon_svg =
      'assets/images/live_tv/play_icon.svg';

  static const String assets_images_live_tv_selection_icon_svg =
      'assets/images/live_tv/selection_icon.svg';

  static const String assets_images_live_tv_sports_image_png =
      'assets/images/live_tv/sports_image.png';

  static const String assets_images_live_tv_travel_image_png =
      'assets/images/live_tv/travel_image.png';

  static const String assets_images_live_tv_type_drodown_svg =
      'assets/images/live_tv/type_drodown.svg';

  static const String assets_images_login_images_animation_png =
      'assets/images/login_images/animation.png';

  static const String assets_images_login_images_app_hotstar_png =
      'assets/images/login_images/app_hotstar.png';

  static const String assets_images_login_images_app_prime_png =
      'assets/images/login_images/app_prime.png';

  static const String assets_images_login_images_app_sonyliv_png =
      'assets/images/login_images/app_sonyliv.png';

  static const String assets_images_login_images_app_sunnxt_png =
      'assets/images/login_images/app_sunnxt.png';

  static const String assets_images_login_images_app_zee5_png =
      'assets/images/login_images/app_zee5.png';

  static const String assets_images_login_images_background_login_png =
      'assets/images/login_images/background_login.png';

  static const String assets_images_login_images_bulb_light_png =
      'assets/images/login_images/bulb_light.png';

  static const String assets_images_login_images_edit_preference_png =
      'assets/images/login_images/edit_preference.png';

  static const String assets_images_login_images_frame_logo_png =
      'assets/images/login_images/frame_logo.png';

  static const String assets_images_login_images_gift_png =
      'assets/images/login_images/gift.png';

  static const String assets_images_login_images_homepage_tv_2_png =
      'assets/images/login_images/homepage_tv_2.png';

  static const String assets_images_login_images_img_1_png =
      'assets/images/login_images/img_1.png';

  static const String assets_images_login_images_img_2_png =
      'assets/images/login_images/img_2.png';

  static const String assets_images_login_images_img_3_png =
      'assets/images/login_images/img_3.png';

  static const String assets_images_login_images_india_flag_svg =
      'assets/images/login_images/india_flag.svg';

  static const String assets_images_login_images_mobile_otp_hand_svg =
      'assets/images/login_images/mobile_otp_hand.svg';

  static const String assets_images_login_images_next_icon_svg =
      'assets/images/login_images/next_icon.svg';

  static const String assets_images_login_images_notification_add_png =
      'assets/images/login_images/notification_add.png';

  static const String assets_images_login_images_off_toggle_png =
      'assets/images/login_images/off_toggle.png';

  static const String assets_images_login_images_point_earned_png =
      'assets/images/login_images/point_earned.png';

  static const String assets_images_login_images_profile_image_png =
      'assets/images/login_images/profile_Image.png';

  static const String assets_images_login_images_toggle_on_png =
      'assets/images/login_images/toggle_on.png';

  static const String assets_images_login_images_triangles_svg =
      'assets/images/login_images/triangles.svg';

  static const String assets_images_login_images_verify_otp_svg =
      'assets/images/login_images/verify_otp.svg';

  static const String assets_images_login_images_watch_time_png =
      'assets/images/login_images/watch_time.png';

  static const String assets_images_nointernet_svg =
      'assets/images/nointernet.svg';

  static const String assets_images_notify_me_button_svg =
      'assets/images/notify_me_button.svg';

  static const String assets_images_onboarding_images_blur_gift_png =
      'assets/images/onboarding_images/blur_gift.png';

  static const String assets_images_onboarding_images_hand_mobile_png =
      'assets/images/onboarding_images/hand_mobile.png';

  static const String assets_images_onboarding_images_handsome_modern_guy_png =
      'assets/images/onboarding_images/handsome-modern-guy.png';

  static const String assets_images_onboarding_images_int_lang_icon_svg =
      'assets/images/onboarding_images/int_lang_icon.svg';

  static const String assets_images_onboarding_images_language_tab_icon_svg =
      'assets/images/onboarding_images/language_tab_icon.svg';

  static const String
      assets_images_onboarding_images_onboarding_arrow_indiicator_1_png =
      'assets/images/onboarding_images/onboarding_arrow_indiicator_1.png';

  static const String
      assets_images_onboarding_images_onboarding_arrow_indiicator_2_png =
      'assets/images/onboarding_images/onboarding_arrow_indiicator_2.png';

  static const String
      assets_images_onboarding_images_onboarding_arrow_indiicator_3_png =
      'assets/images/onboarding_images/onboarding_arrow_indiicator_3.png';

  static const String
      assets_images_onboarding_images_onboarding_background_1_png =
      'assets/images/onboarding_images/onboarding_background_1.png';

  static const String
      assets_images_onboarding_images_onboarding_background_1_svg =
      'assets/images/onboarding_images/onboarding_background_1.svg';

  static const String assets_images_onboarding_images_onboarding_blure_1_png =
      'assets/images/onboarding_images/onboarding_blure_1.png';

  static const String assets_images_onboarding_images_select_topic_icon_svg =
      'assets/images/onboarding_images/select_topic_icon.svg';

  static const String
      assets_images_onboarding_images_splash_screen_background_svg =
      'assets/images/onboarding_images/splash_screen_background.svg';

  static const String assets_images_onboarding_images_three_emoji_png =
      'assets/images/onboarding_images/three_emoji.png';

  static const String assets_images_plan_images_plan_0_png =
      'assets/images/plan_images/plan_0.png';

  static const String assets_images_plan_images_plan_1_png =
      'assets/images/plan_images/plan_1.png';

  static const String assets_images_plan_images_plan_2_png =
      'assets/images/plan_images/plan_2.png';

  static const String assets_images_play_button_svg =
      'assets/images/play_button.svg';

  static const String assets_images_profile_images_about_svg =
      'assets/images/profile_images/about.svg';

  static const String assets_images_profile_images_add_profile_image_svg =
      'assets/images/profile_images/add_profile_image.svg';

  static const String assets_images_profile_images_avatar_1_png =
      'assets/images/profile_images/avatar_1.png';

  static const String assets_images_profile_images_avatar_10_png =
      'assets/images/profile_images/avatar_10.png';

  static const String assets_images_profile_images_avatar_11_png =
      'assets/images/profile_images/avatar_11.png';

  static const String assets_images_profile_images_avatar_12_png =
      'assets/images/profile_images/avatar_12.png';

  static const String assets_images_profile_images_avatar_13_png =
      'assets/images/profile_images/avatar_13.png';

  static const String assets_images_profile_images_avatar_2_png =
      'assets/images/profile_images/avatar_2.png';

  static const String assets_images_profile_images_avatar_3_png =
      'assets/images/profile_images/avatar_3.png';

  static const String assets_images_profile_images_avatar_4_png =
      'assets/images/profile_images/avatar_4.png';

  static const String assets_images_profile_images_avatar_5_png =
      'assets/images/profile_images/avatar_5.png';

  static const String assets_images_profile_images_avatar_6_png =
      'assets/images/profile_images/avatar_6.png';

  static const String assets_images_profile_images_avatar_7_png =
      'assets/images/profile_images/avatar_7.png';

  static const String assets_images_profile_images_avatar_8_png =
      'assets/images/profile_images/avatar_8.png';

  static const String assets_images_profile_images_avatar_9_png =
      'assets/images/profile_images/avatar_9.png';

  static const String assets_images_profile_images_contact_us_top_banner_svg =
      'assets/images/profile_images/contact_us_top_banner.svg';

  static const String assets_images_profile_images_done_button_svg =
      'assets/images/profile_images/done_button.svg';

  static const String assets_images_profile_images_edit_svg =
      'assets/images/profile_images/edit.svg';

  static const String assets_images_profile_images_edit_button_svg =
      'assets/images/profile_images/edit_button.svg';

  static const String assets_images_profile_images_help_support_svg =
      'assets/images/profile_images/help_support.svg';

  static const String assets_images_profile_images_library_icon_svg =
      'assets/images/profile_images/library_icon.svg';

  static const String assets_images_profile_images_my_plan_svg =
      'assets/images/profile_images/my_plan.svg';

  static const String assets_images_profile_images_new_edit_icon_svg =
      'assets/images/profile_images/new_edit_icon.svg';

  static const String assets_images_profile_images_new_profile_png =
      'assets/images/profile_images/new_profile.png';

  static const String assets_images_profile_images_phone_svg =
      'assets/images/profile_images/phone.svg';

  static const String assets_images_profile_images_preference_svg =
      'assets/images/profile_images/preference.svg';

  static const String assets_images_profile_images_settings_new_svg =
      'assets/images/profile_images/settings_new.svg';

  static const String assets_images_profile_images_sign_out_svg =
      'assets/images/profile_images/sign_out.svg';

  static const String assets_images_profile_images_switch_users_svg =
      'assets/images/profile_images/switch_users.svg';

  static const String assets_images_profile_images_tv_remote_svg =
      'assets/images/profile_images/tv-remote.svg';

  static const String assets_images_profile_images_tv_image_png =
      'assets/images/profile_images/tv_image.png';

  static const String assets_images_search_images_banner_1_svg =
      'assets/images/search_images/Banner 1.svg';

  static const String assets_images_search_images_banner_2_svg =
      'assets/images/search_images/Banner 2.svg';

  static const String assets_images_search_images_banner_3_svg =
      'assets/images/search_images/Banner 3.svg';

  static const String assets_images_search_images_banner_4_svg =
      'assets/images/search_images/Banner 4.svg';

  static const String assets_images_search_images_banner_5_svg =
      'assets/images/search_images/Banner 5.svg';

  static const String assets_images_search_images_banner_6_svg =
      'assets/images/search_images/Banner 6.svg';

  static const String assets_images_search_images_banner_7_svg =
      'assets/images/search_images/Banner 7.svg';

  static const String assets_images_search_images_banner_8_svg =
      'assets/images/search_images/Banner 8.svg';

  static const String assets_images_search_images_dummy_image_png =
      'assets/images/search_images/dummy_image.png';

  static const String assets_images_search_images_poster1_svg =
      'assets/images/search_images/poster1.svg';

  static const String assets_images_search_images_poster2_svg =
      'assets/images/search_images/poster2.svg';

  static const String assets_images_search_images_poster3_svg =
      'assets/images/search_images/poster3.svg';

  static const String assets_images_search_images_poster4_svg =
      'assets/images/search_images/poster4.svg';

  static const String assets_images_search_images_poster5_svg =
      'assets/images/search_images/poster5.svg';

  static const String assets_images_search_images_poster6_svg =
      'assets/images/search_images/poster6.svg';

  static const String assets_images_search_images_poster7_svg =
      'assets/images/search_images/poster7.svg';

  static const String assets_images_search_images_poster8_svg =
      'assets/images/search_images/poster8.svg';

  static const String assets_images_unselected_home_svg =
      'assets/images/unselected_home.svg';

  static const String assets_json_faq_data_json = 'assets/json/faq_data.json';

  static const String assets_json_loading_json = 'assets/json/loading.json';

  static const String assets_sounds_speech_to_text_cancel_m4r =
      'assets/sounds/speech_to_text_cancel.m4r';

  static const String assets_sounds_speech_to_text_listening_m4r =
      'assets/sounds/speech_to_text_listening.m4r';

  static const String assets_sounds_speech_to_text_stop_m4r =
      'assets/sounds/speech_to_text_stop.m4r';

  static const String assets_splash_video_dor_splash_video_mp4 =
      'assets/splash_video/dor_splash_video.mp4';

  static const String assets_splash_video_splash_intro_mov =
      'assets/splash_video/splash_intro.mov';

  static const String assets_txt_files_about_threesixty_txt =
      'assets/txt_files/about_threesixty.txt';

  static const String assets_txt_files_privacy_policy_txt =
      'assets/txt_files/privacy_policy.txt';

  static const String assets_txt_files_terms_and_conditions_txt =
      'assets/txt_files/terms_and_conditions.txt';
}
