// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE5CYk1kULzaLEQTg0NcUTiOrBmmmPG3M',
    appId: '1:677807102419:web:2664952e57dc8692013726',
    messagingSenderId: '677807102419',
    projectId: 'dorplay-b3bcf',
    authDomain: 'dorplay-b3bcf.firebaseapp.com',
    storageBucket: 'dorplay-b3bcf.appspot.com',
    measurementId: 'G-G7CF3Y2QQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6mh8MJJNOinUyXsnFGu8wMIluS3xAkNY',
    appId: '1:677807102419:android:99d6d6e76c53442e013726',
    messagingSenderId: '677807102419',
    projectId: 'dorplay-b3bcf',
    storageBucket: 'dorplay-b3bcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBys2jgTnpLboVHS6PADr-fLezl_mmVsPI',
    appId: '1:677807102419:ios:0ec3ea26ed47a573013726',
    messagingSenderId: '677807102419',
    projectId: 'dorplay-b3bcf',
    storageBucket: 'dorplay-b3bcf.appspot.com',
    iosClientId: '677807102419-lsjsj1uhbvmj6ssulie662s5906ofkle.apps.googleusercontent.com',
    iosBundleId: 'tv.dorplay.companion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBys2jgTnpLboVHS6PADr-fLezl_mmVsPI',
    appId: '1:677807102419:ios:0ec3ea26ed47a573013726',
    messagingSenderId: '677807102419',
    projectId: 'dorplay-b3bcf',
    storageBucket: 'dorplay-b3bcf.appspot.com',
    iosClientId: '677807102419-lsjsj1uhbvmj6ssulie662s5906ofkle.apps.googleusercontent.com',
    iosBundleId: 'tv.dorplay.companion',
  );
}
