/// Flutter icons RemoteButtons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RemoteButtons
///      fonts:
///       - asset: fonts/RemoteButtons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RemoteButtons {
  RemoteButtons._();

  static const _kFontFam = 'RemoteButtons';
  static const String? _kFontPkg = null;

  static const IconData left_arrow = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_arrow = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
